import { SphereArticleType } from "@/types/sphere";
import { ISphereArticle } from "./sphere";
import { extractNewsContent } from "@/lib/sphere/news-utils";
const placeholderImages = [
  "/sphere/news/abstract-surface-background-with-various-blue-lines-3d-rendering.jpg",
  "/sphere/news/ai-chip-intelligence-technology-deep-learning.jpg",
  "/sphere/news/business-handshake.jpg",
  "/sphere/news/close-up-hand-typing-calculator.jpg",
  "/sphere/news/colorful-background-with-pattern-different-colors.jpg",
  "/sphere/news/gradient-3d-fluid-background (1).jpg",
  "/sphere/news/gradient-3d-fluid-background (2).jpg",
  "/sphere/news/gradient-3d-fluid-background.jpg",
  "/sphere/news/information-improvement-data-report.jpg",
  "/sphere/news/low-angle-view-modern-ceiling.jpg",
  "/sphere/news/robot-handshake-human-background-futuristic-digital-age.jpg",
  "/sphere/news/satin-soft-blue-abstract-creative-background-design.jpg",
];

const items: Omit<ISphereArticle, "title" | "description">[] = [
  {
    id: "69",
    image: "",
    createdAt: "2025-08-27",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/8-High-Profile-Court-Battles-Emerge-on-Transfer-Pricing-Issues.mdx",
  },
  {
    id: "68",
    image: "",
    createdAt: "2025-08-25",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/7-Economic-Substance-Principle-Gains-Traction-in-IRS-Audits.mdx",
  },
  {
    id: "67",
    image: "",
    createdAt: "2025-08-20",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/6-IRS-Boosts-Enforcement-and-Penalties-on-Transfer-Pricing-Violations.mdx",
  },
  {
    id: "66",
    image: "",
    createdAt: "2025-08-18",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/5-Focus-Sharpens-on-Transfer-Pricing-for-Intangible-Asset-Deals.mdx",
  },
  {
    id: "65",
    image: "",
    createdAt: "2025-08-13",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/4-Tighter-Rules-Issued-on-Adjustments-for-High-Value-Intangibles.mdx",
  },
  {
    id: "64",
    image: "",
    createdAt: "2025-08-11",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/3-Interim-IRS-Guidance-Eases-Transition-to-New-Transfer-Pricing-Rules.mdx",
  },
  {
    id: "63",
    image: "",
    createdAt: "2025-08-06",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/2-US-Aligns-Transfer-Pricing-for-Distributors-with-OECD-Amount-B.mdx",
  },
  {
    id: "62",
    image: "",
    createdAt: "2025-08-04",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/10-US-Transfer-Pricing-Shifts-Closer-to-Global-Tax-Standards.mdx",
  },
  {
    id: "61",
    image: "",
    createdAt: "2025-07-30",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/1-IRS-Unveils-Simplified-Approach-for-Transfer-Pricing-Compliance.mdx",
  },
  {
    id: "60",
    image: "",
    createdAt: "2025-07-28",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/9-Focus-Areas-Intangibles-Financial-Transactions-and-Hard-to-Value-Assets.mdx",
  },
  {
    id: "59",
    image: "",
    createdAt: "2025-07-23",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/8-Advanced-Pricing-Agreements-APA-Framework.mdx",
  },
  {
    id: "58",
    image: "",
    createdAt: "2025-07-21",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/7-Guidance-on-Statistical-Methods-Range-and-Loss-Markers.mdx",
  },
  {
    id: "57",
    image: "",
    createdAt: "2025-07-16",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/6-Response-to-Global-Minimum-Tax-Pillar-2.mdx",
  },
  {
    id: "56",
    image: "",
    createdAt: "2025-07-14",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/5-Country-by-Country-Reporting-and-Public-Disclosure.mdx",
  },
  {
    id: "55",
    image: "",
    createdAt: "2025-07-09",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/4-Detailed-Content-Requirements-for-Files.mdx",
  },
  {
    id: "54",
    image: "",
    createdAt: "2025-07-07",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/3-Tightened-Documentation-Deadlines-and-New-Penalties.mdx",
  },
  {
    id: "53",
    image: "",
    createdAt: "2025-07-02",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/2-Mandatory-Master-File-and-Local-File.mdx",
  },
  {
    id: "52",
    image: "",
    createdAt: "2025-06-30",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/10-Court-Decisions-and-Recent-HMRC-Practice.mdx",
  },
  {
    id: "51",
    image: "",
    createdAt: "2025-06-25",
    type: SphereArticleType.News,
    country: "GB",
    md: "UK/1-Direct-Application-of-OECD-Guidelines-and-Arms-Length-Principle.mdx",
  },
  {
    id: "50",
    image: "",
    createdAt: "2025-06-23",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/9-Exchange-of-Information-and-Disclosure-Transparency.mdx",
  },
  {
    id: "49",
    image: "",
    createdAt: "2025-06-18",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/8-BEPS-Pillar-Two-GloBE-Developments.mdx",
  },
  {
    id: "48",
    image: "",
    createdAt: "2025-06-16",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/7-Advance-Pricing-Agreement-APA-Program-Updates.mdx",
  },
  {
    id: "47",
    image: "",
    createdAt: "2025-06-11",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/6-Mexican-Comparable-Search-Preferences-and-Local-Data.mdx",
  },
  {
    id: "46",
    image: "",
    createdAt: "2025-06-09",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/5-Enhanced-Focus-on-Intangibles-and-DEMPE.mdx",
  },
  {
    id: "45",
    image: "",
    createdAt: "2025-06-04",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/4-Stricter-Penalties-for-Non-Compliance.mdx",
  },
  {
    id: "44",
    image: "",
    createdAt: "2025-06-02",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/3-Country-by-Country-Reporting-Obligations.mdx",
  },
  {
    id: "43",
    image: "",
    createdAt: "2025-05-28",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/2-Mandatory-Master-File-Local-File-and-Informative-Return.mdx",
  },
  {
    id: "42",
    image: "",
    createdAt: "2025-05-26",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/10-Latest-Litigation-and-Audit-Trends.mdx",
  },
  {
    id: "41",
    image: "",
    createdAt: "2025-05-21",
    type: SphereArticleType.News,
    country: "MX",
    md: "Mexico/1-Alignment-with-OECD-Transfer-Pricing-Guidelines.mdx",
  },
  {
    id: "40",
    image: "",
    createdAt: "2025-05-19",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Tougher_Penalties_without_Documentation.mdx",
  },
  {
    id: "39",
    image: "",
    createdAt: "2025-05-14",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Shorter_Filing_Window_and_Electronic_Documentation.mdx",
  },
  {
    id: "38",
    image: "",
    createdAt: "2025-05-12",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Mandatory_Public_Country_by_Country_Reporting.mdx",
  },
  {
    id: "37",
    image: "",
    createdAt: "2025-05-07",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Integration_with_Customs_Valuation.mdx",
  },
  {
    id: "36",
    image: "",
    createdAt: "2025-05-05",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Guidance_on_Statistical_Methods_and_Range.mdx",
  },
  {
    id: "35",
    image: "",
    createdAt: "2025-04-30",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Documentation_Structure_per_the_2020_Decree.mdx",
  },
  {
    id: "34",
    image: "",
    createdAt: "2025-04-28",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Direct_Implementation_of_OECD_Guidance.mdx",
  },
  {
    id: "33",
    image: "",
    createdAt: "2025-04-23",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Best_Method_Principle_Clarified.mdx",
  },
  {
    id: "32",
    image: "",
    createdAt: "2025-04-21",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/BEPS_Pillar_2_and_Hybrids_New_Compliance_Standards.mdx",
  },
  {
    id: "31",
    image: "",
    createdAt: "2025-04-16",
    type: SphereArticleType.News,
    country: "IT",
    md: "Italy/Advanced_Pricing_Agreements_Expanded_Framework.mdx",
  },
  {
    id: "30",
    image: "",
    createdAt: "2025-04-14",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/9-Key-TP-Challenges-for-Global-Capability-Centres-GCCs.mdx",
  },
  {
    id: "29",
    image: "",
    createdAt: "2025-04-09",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/8-Master-File-Local-File-CbC-Reporting-Deadlines.mdx",
  },
  {
    id: "28",
    image: "",
    createdAt: "2025-04-07",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/7-BEPS-Pillar-2-15-Percent-Global-Minimum-Tax-Preparations.mdx",
  },
  {
    id: "27",
    image: "",
    createdAt: "2025-04-02",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/6-Alignment-with-OECD-Transfer-Pricing-Guidelines-2022.mdx",
  },
  {
    id: "26",
    image: "",
    createdAt: "2025-03-31",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/5-Power-to-Revise-TP-Orders.mdx",
  },
  {
    id: "25",
    image: "",
    createdAt: "2025-03-26",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/4-Tolerance-Band-Notification.mdx",
  },
  {
    id: "24",
    image: "",
    createdAt: "2025-03-24",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/3-New-Income-Tax-Bill-2025-AE-Definition-and-ALP-Calculation.mdx",
  },
  {
    id: "23",
    image: "",
    createdAt: "2025-03-19",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/2-Expanded-Safe-Harbour-Rules-and-Higher-Turnover-Thresholds.mdx",
  },
  {
    id: "22",
    image: "",
    createdAt: "2025-03-17",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/10-Broader-Safe-Harbour-Digital-and-Auto-Sector.mdx",
  },
  {
    id: "21",
    image: "",
    createdAt: "2025-03-12",
    type: SphereArticleType.News,
    country: "IN",
    md: "India/1-Three-Year-Block-Assessment-for-Transfer-Pricing.mdx",
  },
  {
    id: "20",
    image: "",
    createdAt: "2025-03-10",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/9-Enhanced-Enforcement-High-Risk-Transactions.mdx",
  },
  {
    id: "19",
    image: "",
    createdAt: "2025-03-05",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/8-New-Focus-on-Intangibles-and-DEMPE-Functions.mdx",
  },
  {
    id: "18",
    image: "",
    createdAt: "2025-03-03",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/7-OECD-Style-Advance-Pricing-Arrangements..mdx",
  },
  {
    id: "17",
    image: "",
    createdAt: "2025-02-26",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/6-Country-by-Country-Reporting.mdx",
  },
  {
    id: "16",
    image: "",
    createdAt: "2025-02-24",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/5-Pillar-2-Global-Minimum-Tax-Adoption-and-Legislation.mdx",
  },
  {
    id: "15",
    image: "",
    createdAt: "2025-02-19",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/4-Revised-Guidance-on-Arms-Length-Range-and-Statistical-Applications.mdx",
  },
  {
    id: "14",
    image: "",
    createdAt: "2025-02-17",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/3-Substantial-Penalties-for-Non-Compliance.mdx",
  },
  {
    id: "13",
    image: "",
    createdAt: "2025-02-12",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/2-Streamlined-Documentation-Requirements-and-Filing-Deadlines..mdx",
  },
  {
    id: "12",
    image: "",
    createdAt: "2025-02-10",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/10-Litigation-Trends-and-Recent-Case-Law.mdx",
  },
  {
    id: "11",
    image: "",
    createdAt: "2025-02-05",
    type: SphereArticleType.News,
    country: "CA",
    md: "Canada/1-Continued-Alignment-with-OECD-Guidelines.mdx",
  },
  {
    id: "10",
    image: "",
    createdAt: "2025-02-03",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/9-Landmark-Alcoa-Transfer-Pricing-Ruling.mdx",
  },
  {
    id: "9",
    image: "",
    createdAt: "2025-01-29",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/8-15-Percent-Global-Minimum-Tax-Now-in-Effect.mdx",
  },
  {
    id: "8",
    image: "",
    createdAt: "2025-01-27",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/7-ATO-Raises-the-Bar-on-Intangibles-Review.md.mdx",
  },
  {
    id: "7",
    image: "",
    createdAt: "2025-01-22",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/6-Alignment-with-Latest-OECD-TP-Guidelines.mdx",
  },
  {
    id: "6",
    image: "",
    createdAt: "2025-01-20",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/5-Stricter-Exemptions-for-CbC-Reporting.mdx",
  },
  {
    id: "5",
    image: "",
    createdAt: "2025-01-15",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/4-Public-Country-by-Country-Reporting-Goes-Live.mdx",
  },
  {
    id: "4",
    image: "",
    createdAt: "2025-01-13",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/3-New-Local-File-V4.0-Reporting-Standards.mdx",
  },
  {
    id: "3",
    image: "",
    createdAt: "2025-01-08",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/2-Major-Changes-to-Thin-Capitalisation-Rules.mdx",
  },
  {
    id: "2",
    image: "",
    createdAt: "2025-01-06",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/10-ATO-Intensifies-Reporting-and-Analytics.mdx",
  },
  {
    id: "1",
    image: "",
    createdAt: "2025-01-01",
    type: SphereArticleType.News,
    country: "AU",
    md: "Australia/1-ATO-Tightens-Scrutiny-of-Related-Party-Financing.md.mdx",
  },
  {
    id: "70",
    image: "",
    createdAt: "2025-01-01",
    type: SphereArticleType.News,
    country: "US",
    md: "United states/9-Documentation-and-Disclosure-Rules-Tightened-for-2025.mdx",
  },
];
export const news: ISphereArticle[] = items.map((item, index) => {
  const { title, description } = extractNewsContent(`news/${item.md}`);
  return {
    ...item,
    id: `news-${index + 1}`,
    title,
    description,
    image: placeholderImages[index % placeholderImages.length],

    hideInThisArticle: true,
    md: `news/${item.md}`,
  };
});
